
# Agradecimentos {#agradecimentos .unnumbered}  

**Parcerias Institucionais**   

Conselho Nacional de Desenvolvimento Científico e Tecnológico – CNPq  
*Deutsche Gesellschaft für Internationale Zusammenarbeit Gmbh – GIZ*  
Empresa Brasileira de Pesquisa Agropecuária - Embrapa  
Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do Rio de Janeiro – FAPERJ  
Fundo Brasileiro para a Biodiversidade – Funbio  
Fundo Clima Global Environment Fund – GEF  
*Gordon and Betty Moore Foundation*  
Jardim Botânico de Nova York - JBNY  
Jardim Botânico do Rio de Janeiro – JBRJ  
Instituto de Pesquisas Ecológicas – IPÊ  
Programa Áreas Protegidas da Amazônia – Arpa  
Programa das Nações Unidas para o Desenvolvimento – PNUD  
*United States Agency for International Development – Usaid*  
*World Wildlife Fund for Nature* - WWF Brasil 

**Participações** 

Agradecemos a todas as pessoas e instituições que apoiam e viabilizam o Programa Monitora, seja no fomento, na captação de recursos, nas capacitações, na coleta de dados, nas análises, na divulgação de resultados, na internalização de suas rotinas e processos de trabalho, bem como na execução das diversas pequenas tarefas cotidianas relacionadas à sua implementação. Apresentamos a seguir algumas entidades e pessoas que tornaram essa publicação possível.   


**Coordenação de Monitoramento da Biodiversidade – COMOB** 

Alberto Costa de Paula, Arthur Brant Pereira, Bruno Lenhaverde Sandy, Dárlison Fernandes Carvalho de Andrade, Jumara Marques Souza, Laura Moreira de Andrade Reis, Laura Shizue Moriga Masuda, Leonardo Kenji Miyashita, Marcelo Lima Reis, Márcio Huerara Prado, Rachel Klaczko Acosta, Silvia Carla Galuppo, Tathiana Chaves de Souza e Ugo José Borba Bezerra.   



**Centros Nacionais de Pesquisa e Conservação - CBC, CEMAVE, CENAP e CPB** 

Alexandre Bonesso Sampaio, Arlindo Gomes Filho, Danilo Camargo Vieira Correa, Elildo Alves Ribeiro de Carvalho Junior, Gerson Buss, Henrique Gonçalves, Isabela Freitas Oliveira, Marcos de Souza Fialho, Onildo Marini Filho, Rafael Suertegaray Rossato, Renata Bocorny de Azevedo e Ricardo Sampaio.  

**Núcleos de Gestão Integrada ICMBio Tefé** 

Richard Hatakeyama  


**Núcleos de Gestão Integrada ICMBio Roraima**   

Thiago Orsi Laranjeiras  


**Parque Nacional do Descobrimento -ICMBio**  

Rafaela Campostrini Forzza  
*Bolsista de produtividade do CNPq-303059/2020-6 e da FAPERJ - E‐26/200.967/2022*  


**Jardim Botânico do Rio de Janeiro – JBRJ** 

Adriano da Silva Lima, Daniel da Silva Costa,  Herison Medeiros, Isaías Brasil, Lívia Souza Silva, Marina Landeiro, Rafaela Campostrini Forzza e Wendeson Castro.  


**Jardim Botânico de Nova York – NYBG**   

Aldeciano Alves Soares, Edilson Consuelo de Oliveira e Flávio Amorim Obermuller.  

 

**Universidade de São Paulo - USP**

Renato Mello-Silva  

 

**Universidade Federal do Paraná - UFPR**

Paulo Labiak  
*Bolsista de produtividade do CNPq-303330/2022-8*  


**Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Sustentáveis - Ibama**  

Felipe Guimarães  


**Embrapa Recursos Genéticos e Biotecnologia** 

Marcelo Fragomeni Simon, Aécio Amaral Santos, Bruno Machado Teles Walter, Luciano de Bem Bianchetti, Valdeci Ferreira Gomes e Ismael da Silva Gomes.  

 
**Serviço Florestal Brasileiro - SFB**  

Dárlison Fernandes Carvalho de Andrade, Humberto Mesquita e Tiago Cruz.  



Agradecemos especialmente aos envolvidos na coleta de dados nas mais de 56 unidades de conservação federais listadas no **Apêndice X**. 
  