
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, echo=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)
library(data.table)
library(descr)
library(RColorBrewer)
library(kableExtra)
library(knitr)
library(DT)
library(plotly)
library(ggthemes)
library(forcats)
library(leaflet)
library(sf)
library(rgdal)
library(treemapify)
library(reshape2)
library(randomcoloR)
library(survminer)
library(renv)
```

# (APPENDIX) Apêndices {- #apendice}

\pagestyle{headings}

## Apêndice A - Lista de coletores {.appendix}

\hspace{1.5cm}

## Apêndice B - Evolução do estágio de implementação do Programa {.appendix}

\hspace{1.5cm}

## Apêndice C - Lista de mamíferos {.appendix}

\hspace{1.5cm}


```{r tabela mamíferos}
#| label: tbl-lista-mamiferos
#| echo: false
#| message: false
#| warning: false
#| cache: true
#| fig.pos: 'H'
#| out.width: '70%'
#| tab-cap: "Mamíferos registrados nas amostragens diurnas em transecções lineares do Programa Monitora, no período de 2014 a 2022. Os números entre parênteses correspondem ao número de espécies registradas para o táxon. Em vermelho estão os táxons ameaçados e sua respectiva categoria de ameaça. As espécies 'Deficientes em Dados (DD)' também estão indicadas."

tabela_mamiferos <- read.csv2("dados/tabelas/tabela_3.4.1.csv", encoding="UTF-8")

tab_mamiferos <- kbl(tabela_mamiferos,
             booktabs = TRUE,
             longtable = TRUE,
             # caption = "Espécies de aves migratórias e seus respectivos escores de vulnerabilidade usados na análise do Zonation.*",
            col.names = c("Ordem", "Família", "Táxon")) %>%
    column_spec(3, italic = TRUE) %>% 
kable_styling(full_width = F, bootstrap_options = c("striped", "hover", "condensed", "responsive"), latex_options = c("repeat_header"), repeat_header_text = "\\textit{(continuação)}")

tab_mamiferos

```



## Apêndice D - Lista de aves {.appendix}


```{r tabela aves}
#| label: tbl-lista-aves
#| echo: false
#| message: false
#| warning: false
#| cache: true
#| fig.pos: 'H'
#| out.width: '70%'
#| tab-cap: "Táxons (gêneros e espécies) de aves registrados nas unidades de conservação amostradas no período de 2014 a 2022."

tabela_aves <- read.csv2("dados/tabelas/tabela_3.4.2.csv", encoding="UTF-8")

tab_aves <- kbl(tabela_aves,
             booktabs = TRUE,
             longtable = TRUE,
             # caption = "Espécies de aves migratórias e seus respectivos escores de vulnerabilidade usados na análise do Zonation.*",
            col.names = c("Ordem", "Família", "Táxon")) %>%
    column_spec(3, italic = TRUE) %>% 
kable_styling(full_width = F, bootstrap_options = c("striped", "hover", "condensed", "responsive"), latex_options = c("repeat_header"), repeat_header_text = "\\textit{(continuação)}")


tab_aves

```


