---
title: "Consideraçõs finais"
bibliography: [referencias_cap06.bib]
---

</br>

**Rodrigo Silva Pinto Jorge^1^**, **Marcos de Sousa Fialho^2^** & **Arlindo Gomes Filho^2^** 

 </br>

1. Coordenação de Monitoramento da Biodiversidade - COMOB  
*Instituto Chico Mendes de Conservação da Biodiversidade – ICMBio*  
*Complexo Administrativo EQSW 103/104 s/n*  
*70670-350 Brasília, DF*  


2. Centro Nacional de Pesquisa e Conservação de Aves Silvestres – CEMAVE  
*Instituto Chico Mendes de Conservação da Biodiversidade – ICMBio*  
*BR-230 Km 10*  
*Floresta Nacional da Restinga de Cabedelo*  
*58108-012 Cabedelo, PB*  

</br>
 

<p><font size="2">

<b>Como citar</b>:  Jorge, R. S. P.; Fialho, M. S. & Gomes-Filho, A. Considerações finais. In:  Programa Nacional de Monitoramento da Biodiversidade – Programa Monitora, Subprograma Terrestre, Componente Florestal. Relatório 2014-2022. Instituto Chico Mendes de Conservação da Biodiversidade, Brasília, 2024.

</font></p>


</br>



A aplicação dos protocolos do Componente Florestal do Programa Monitora de 2014 a 2022, a despeito de algumas limitações, gerou dados importantes acerca do estado da biodiversidade em muitas unidades de conservação. Em alguns casos, os registros já se estendem por mais de 10 anos e, com a continuidade do Programa, tais informações se tornarão gradativamente ainda mais valiosas para o entendimento do estado da biodiversidade e da efetividade do sistema de unidades de conservação federais do país.  

Até o momento, as análises dos dados sugerem certa estabilidade dos ambientes e populações das unidades de conservação amostradas. Não foram observadas mudanças significativas na estrutura da vegetação, as flutuações das tribos de borboletas frugívoras ocorreram sem picos acentuados, à exceção de casos específicos, como nos locais com floração e morte de tabocais, no extremo ocidental da Amazônia e, embora tenham sido registradas algumas populações de mamíferos e aves com abundâncias relativamente baixas, a maioria apresentou taxa de avistamento estável ou em crescimento ao longo dos anos.  

Nas 110 unidades amostrais (UAs) de plantas implementadas 96 no Bioma Amazônico, oito na Mata Atlântica e seis no Cerrado), 20.744 indivíduos foram mensurados até a última amostragem de 2022.  Os resultados até o momento indicam que as variáveis avaliadas permaneceram estáveis, sugerindo que a maior parte das florestas monitoradas não vem sofrendo impactos significativos ao longo do período de monitoramento e que as unidades de conservação estão sendo efetivas em proteger sua biodiversidade.  

Com um esforço amostral total de 90.320 armadilhas-dia, o Programa Monitora registrou, em nível de tribo, 85.386 borboletas frugívoras, em 50 unidades de conservação federais. O monitoramento resultou na descoberta de novas espécies para a ciência e novas ocorrências para o Brasil. De modo geral, o índice de abundância das borboletas indicadoras de florestas fechadas/preservadas e abertas/perturbadas permaneceu estável ao longo dos anos, sem evidenciar aumentos ou diminuições significativas consecutivas.  

Eventos climáticos e ambientais parecem influenciar substancialmente o aumento ou diminuição das tribos indicadoras em nível regional. Isso é evidente em regiões do leste e sudeste da Amazônia, conhecidas como o "arco do desmatamento", onde se observaram tendências de redução na abundância na maioria dos anos. Perturbações locais amplificam esse efeito, como demonstrado pelo aumento da abundância de tribos indicadoras de florestas abertas no Acre, causado pela queda de tabocais.  
 
Por fim, para os alvos mamíferos e aves, a aplicação do protocolo básico em 53 unidades de conservação federais nos biomas Amazônia, Cerrado e Mata Atlântica, totalizou cerca de 25 mil quilômetros percorridos, distribuídos em 140 unidades amostrais. Cerca de 23 mil avistamentos foram realizados, totalizando 131 espécies de mamíferos (60 gêneros) e 29 de aves (13 gêneros). A maioria dos registros correspondeu a espécies diurnas das ordens de mamíferos Primates e Rodentia, e das ordens de aves Galliformes e Tinamiformes. Trinta e cinco espécies ameaçadas foram registradas, equivalendo a 8% do total de registros. Espécies exóticas ou invasoras foram raras, sendo representadas por apenas três registros em duas unidades de conservação no bioma Mata Atlântica.  

A maior parte das populações analisadas permaneceu estável. A análise de tendências populacionais incluiu 165 populações de 57 espécies, e revelou que a maioria (92,7%) destas não apresentou variação significativa, apesar de 6,7% terem apresentado tendência de declínio. O índice de tendências da biodiversidade para o conjunto de unidades de conservação, permaneceu estável ao longo do monitoramento, sugerindo que as unidades de conservação monitoradas têm sido efetivas para a conservação das espécies-alvo. Ressalta-se que a série temporal ainda é relativamente curta e que as espécies com melhores dados são, em sua maioria, espécies comuns e ecologicamente flexíveis. Além de avaliar a efetividade das unidades de conservação, este monitoramento também tem contribuído no processo de avaliação do risco de extinção das espécies de mamíferos e aves brasileiros.  

Contudo, aperfeiçoamentos são possíveis e oportunos. Além das recomendações específicas relativas a cada um dos alvos, apresentadas em seus respectivos capítulos, descrevemos a seguir algumas recomendações gerais, com vistas ao aprimoramento do Componente Florestal do Programa Monitora.  

Poucas unidades de conservação do Cerrado e da Mata Atlântica participam atualmente do Programa, sendo necessário ampliar a adesão de unidades de conservação desses biomas.  

Com relação ao monitoramento de borboletas frugívoras, na Amazônia há uma lacuna de amostragens na região climática Noroeste, indicando a pertinência da implementação do protocolo básico desse alvo global em pelo menos três unidades, preferencialmente na ESEC Juami-Japurá, no PARNA do Pico da Neblina e na RESEX Auatí-Paraná. Recomenda-se também a ampliação do número de unidades de conservação com aplicação do protocolo de borboletas frugívoras nas regiões do médio e baixo rio Juruá, áreas de extrema importância biológica e ainda carentes de dados sobre esse grupo. A coleta de dados de borboletas também deve ser incrementada na região climática Sudeste Amazônica, de forma a se alcançar a suficiência amostral mínima de 18 EAs no ano. Para essa região, sugere-se a implementação do protocolo básico de borboletas frugívoras nas RESEX Médio e Baixo Juruá, na FLONA de Tefé, na FLONA de Carajás, na REBIO Nascentes da Serra do Cachimbo e na ESEC Iquê.  

A lacuna amostral da região Noroeste da Amazônia também se aplica aos alvos globais mamíferos e aves, que na Mata Atlântica do Nordeste também têm sido pouco amostrados, em comparação à porção de Mata Atlântica ao sul da Bahia.  

Nesse contexto, apesar da óbvia importância da ampliação gradativa do Programa Monitora, tanto em termos de abrangência espacial, quantidade e diversidade dos componentes monitorados, quanto em número de unidades de conservação participantes, cabe ressaltar o caráter estratégico de se considerar também o aspecto qualitativo nesse processo de crescimento. Nesse sentido, a adesão de novas unidades de conservação deve ser precedida de uma avaliação em relação ao seu potencial de contribuição ao Programa em termos relativos, ou seja, em comparação a outras áreas alternativas ou mesmo aos ganhos advindos da alocação de esforços (recursos financeiros e operacionais) para a consolidação ou ampliação da implementação de alvos em unidades já vinculadas ao Programa.  

O crescimento do Programa não deve se dar meramente em atendimento às demandas ou a situações de oportunidades momentâneas, devendo a inclusão de novas áreas levar em consideração fatores como a redução de lacunas de amostragem em ambientes ecologicamente importantes, a representatividade dos ambientes considerando todo o sistema de unidades de conservação, o potencial de ocorrência de espécies ameaçadas e outros critérios técnicos que venham a ser identificados como relevantes. Devem ser considerados também aspectos operacionais, a exemplo da pré-existência de fontes de recursos financeiros ou o potencial para sua captação, o grau de dificuldade logística, a disponibilidade e comprometimento da equipe da unidade e potencial de estabelecimento de parcerias locais, além da perspectiva de manutenção do Programa em atividade naquela área por um período suficientemente longo que justifique todo o esforço de implementação, visto que qualquer programa de monitoramento pressupõe a regularidade das amostragens em médio e longo prazos.  

Em síntese, é preciso que o Programa Monitora priorize um crescimento estratégico, focado na alocação de recursos financeiros, tempo e energia de forma criteriosa, em áreas potencialmente mais importantes e representativas, que apresentem uma boa relação custo-benefício em termos do esforço institucional investido e a qualidade e importância da informação gerada. Uma abordagem mais estratégica nesse sentido possibilitará, simultaneamente, uma visão mais consistente da efetividade do sistema de unidades de conservação e um aporte de informações relevantes para subsidiar decisões de gestão em nível local e regional.  

O Programa Monitora foi estruturado considerando o princípio da modularidade, de forma que protocolos avançados de amostragem (de maior complexidade) para um determinado alvo possam ser implementados em unidades de conservação que já tenham adotado o protocolo básico deste mesmo alvo. Outro aspecto importante desta modularidade é que as estações amostrais (EAs) de determinado alvo podem tanto ser implementadas simultaneamente, num mesmo ano, quanto de forma gradativa, ao longo dos anos, quando em condições menos favoráveis.  Assim, a estratégia de implementação das EA pode variar, a depender da conciliação da atividade de monitoramento da biodiversidade com outras demandas locais, além da capacidade logística e de pessoal da unidade. Contudo, a experiência acumulada na  aplicação dos protocolos e subsequente  análises dos dados aponta que, na impossibilidade de implementação simultânea (no mesmo ano) de todas as estações amostrais para todos os alvos do componente, como preconizado no Roteiro Metodológico do Programa Monitora (@Nobre_2014), é recomendável a  implementação completa das estações amostrais (três EAs) de pelo menos um mesmo  alvo, em detrimento da implementação parcial (de apenas uma ou duas EAs) de um, dois ou três alvos naquele ano.  Ressaltamos que a implementação sequencial das EAs de um mesmo alvo, ou seja, em anos distintos, impacta negativamente e dificulta a análise dos dados, prejudicando a qualidade das informações geradas pelo Programa.  

O percentual de unidades de conservação não consolidadas (57%), unidades em atividade com um número de EAs inferior ao preconizado como mínimo para todos os alvos, indica que devemos envidar esforços na consolidação da implantação dos protocolos nas unidades de conservação, de forma que estas alcancem pelo menos três estações amostrais implantadas e em operação. Isto se aplica, especialmente, ao Cerrado e à Mata Atlântica, dado que além de contarem com poucas unidades de conservação no Programa, nenhuma delas chegou a atingir a suficiência amostral em qualquer ano para qualquer alvo considerado. Logo, recomenda-se que novas unidades de conservação que venham a participar do Programa promovam a implantação de todas as unidades amostrais para o mesmo alvo em um mesmo ano. Esta situação é um reflexo da inexistência de programas de financiamento extraorçamentário que apoiem a implantação do Programa Monitora nestes biomas, como foi o caso do Programa ARPA na Amazônia. O apoio do Programa ARPA tem sido fundamental para garantir a constância das campanhas de coleta e completude dos conjuntos de dados.  

Durante as campanhas de campo deve-se assegurar que as amostragens sejam realizadas de acordo com as diretrizes estabelecidas no protocolo amostral, em especial quanto ao respeito aos períodos de coleta definidos para cada região e em relação ao esforço amostral (número de dias de amostragens em cada EA). Essa diretriz deve ser constantemente reforçada, seja por meio de atualizações das capacitações, seja durante os Encontros dos Saberes. Outras recomendações que merecem destaque são o atendimento aos períodos indicados para amostragem nas diferentes regiões, no caso das borboletas frugívoras, dado que ainda há unidades amostrando fora dos períodos estabelecidos, e o aprimoramento da precisão das medidas de distância perpendicular à transecção, no caso de mamífero e aves.  

Problemas de insuficiência amostral e análise foram gerados por estações amostrais que se distribuem em diferentes interflúvios numa mesma unidade de conservação. Logo, quando a unidade de conservação ocupar mais de um interflúvio de relevância biogeográfica, recomenda-se que as unidades amostrais do protocolo básico sejam instaladas em um único lado do interflúvio, considerando que os diferentes lados podem apresentar comunidades animais distintas. Sugere-se que essa mesma recomendação seja seguida para a amostragem de unidades de conservação em blocos.  

Por fim, ressaltamos que os dados coletados devem ser sempre repassados à Coordenação do Programa de acordo com suas orientações e em prazo razoável após a realização das campanhas de campo.  

Os dados brutos do monitoramento obtidos através dos protocolos básicos dos alvos globais utilizados para elaboração deste relatório estão disponíveis na [página do Programa Monitora](https://www.gov.br/icmbio/pt-br/assuntos/monitoramento), no sítio eletrônico do ICMBio. Futuramente, esses dados estarão disponíveis no sistema de gestão de dados do Programa Monitora (SISMonitora), que segue em desenvolvimento.   

Vale destacar ainda a disponibilização dos resultados específicos para cada unidade de conservação por meio de uma [plataforma interativa](https://www.gov.br/icmbio/pt-br/assuntos/monitoramento/painel-interativo-relatorio-florestal). Esse é um importante avanço que complementa os resultados gerais deste relatório, pois os painéis permitem que os gestores e a sociedade tenham acesso aos resultados dos diferentes alvos para cada uma das unidades de conservação, possibilitando seu uso como subsídio direto à gestão dessas áreas. Os painéis serão atualizados anualmente assim que os dados coletados em campo sejam validados, eliminando, no curto prazo, o lapso temporal para a disponibilização dos resultados.  

O arranjo que possibilitou a elaboração do presente relatório, com a integração de representantes com habilidade e experiência em ferramentas de análise de dados de biodiversidade de diferentes centros nacionais de pesquisa e conservação e de unidades de conservação, permitirá que se avance na elaboração das análises e dos relatórios referentes aos protocolos avançados. Esse arranjo também servirá de modelo para a realização das análises e elaboração dos relatórios relativos aos alvos básicos, avançados e complementares deste e dos demais subprogramas e componentes do Programa Monitora.  

As inovações tecnológicas e metodológicas para coleta, análise, gestão e interpretação de dados de biodiversidade tem se acelerado nos últimos anos. A gestão do Programa Monitora está atenta a esses avanços e pretende avaliar e discutir com parceiros a realização de testes para incorporação dessas inovações no Monitora, quando pertinentes, de modo a beneficiá-lo, sem, no entanto, desconsiderar os protocolos e métodos estabelecidos. A potencial adoção de inovações ao Programa será avaliada tendo como premissa facilitar a obtenção de dados dos protocolos pelas unidades de conservação, com a simplificação de sua operacionalização e possibilidade de ganho de escala, desde que não se perca conexão com os dados coletados por meio dos protocolos vigentes. Outro aspecto que deve ser mantido e estimulado é a participação social nas diferentes etapas do Programa, com destaque para a coleta de dados e sua posterior discussão coletiva nos Encontros de Saberes. A participação social é uma diretriz do Programa e é tão importante quanto a coleta de dados, pois gera benefícios como o engajamento da sociedade local no debate acerca da conservação do meio ambiente (@Cronemberger_2023).  

Um dos objetivos relevantes na adoção de inovações é agilizar o processo de análise e interpretação dos dados e tornar mais eficiente, amigável e célere a disponibilização dos resultados aos gestores das unidades de conservação e à sociedade. O Programa Monitora precisa entregar seus resultados de forma cada vez mais ágil visando deflagrar, quando pertinente, ações de gestão, no nível local, nas unidades de conservação, ou em nível mais amplo, a exemplo da atualização da Lista de Espécies Ameaçadas de Extinção, dentre outras possibilidades. Pretende-se que, no futuro, os gestores das unidades de conservação contem com ferramentas que destaquem de imediato eventuais alertas decorrentes dos resultados do Programa Monitora na unidade de conservação em que trabalham, já com sugestões de opções de ações práticas de gestão a adotar.  

Dessa forma, pretende-se que o Programa Monitora se torne gradualmente uma ferramenta cada vez mais importante na gestão local das unidades de conservação, além de uma referência na geração e disponibilização de subsídios para atualização e elaboração de políticas públicas envolvendo a biodiversidade.  


</br>

## Referências