
# Equipe {#equipe .unnumbered}  

**ORGANIZAÇÃO** 

Arlindo Gomes Filho  
Bruno Lenhaverde Sandy  
Dárlison Fernandes Carvalho de Andrade  
Elildo Alves Ribeiro de Carvalho Junior  
Onildo João Marini Filho  
Marcos de Souza Fialho  

**REVISÃO** 

Dárlison Fernandes Carvalho de Andrade  
Marcelo Lima Reis  
Rodrigo Pinto Silva Jorge


**TEXTOS**  


**Apresentação**  
Cecília Cronemberger de Faria  


**Programa Nacional de Monitoramento da Biodiversidade – Programa Monitora**  
Dárlison Fernandes Carvalho de Andrade  
Rodrigo Pinto Silva Jorge  


 **Implementação do componente florestal**  
Marcelo Lima Reis  
Jumara Marques Souza  


**Plantas arbóreas e arborescentes**  
Alexandre Bonesso Sampaio  
Bruno Lenhaverde Sandy  
Cecília Cronemberger de Faria  
Dárlison Fernandes Carvalho de Andrade  
Flávio Amorim Obermuller  
Herison Medeiros  
Humberto Mesquisa  
Jumara Marques Souza  
Kátia Torres Ribeiro  
Pualo Labiak  
Rafaela Camponstrini Forzza  
Tiago Cruz  


**Borboletas frugívoras**  
Isabela Freitas Oliveira  
Arlindo Gomes Filho 
Onildo João Marini Filho  


**Mamíferos terrestres de médio e grande porte e aves terrícolas cinegéticas**  
Arlindo Gomes Filho  
Elildo Alves Ribeiro de Carvalho Junior  
Gerson Buss  
Marcelo Lima Reis  
Marcos de Souza Fialho  
Rafael Suertegaray Rossato  
Ricardo Sampaio  
Richard Hatakeyama  
Thiago Orsi Laranjeiras  


**Análise da sinergia entre alvos**  
Arlindo Gomes Filho  
Elildo Alves Ribeiro de Carvalho Junior  
Isabela Freitas Oliveira  
Marcos de Souza Fialho  
Onildo João Marini Filho  


**Considerações finais**  
??????
 
