# Expediente {#expediente .unnumbered}

**REPÚBLICA FEDERATIVA DO BRASIL**
  
  *Presidente*\
Luiz Inácio Lula da Silva 

*Vice-Presidente*\
Geraldo Alckmin

**MINISTÉRIO DO MEIO AMBIENTE**
  
*Ministra*\
Marina Silva

**INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE**
  
*Presidente*\
Mauro Oliveira Pires

*Diretor de Pesquisa, Avaliação e Monitoramento da Biodiversidade*\
Marcelo Marcelino de Oliveira

*Coordenadora Geral de Pesquisa e Monitoramento da Biodiversidade*\
Cecília Cronemberger de Faria 

*Coordenador de Monitoramento da Biodiversidade*\
Rodrigo Silva Pinto Jorge

*Centros Nacionais de Pesquisa e Conservação*\
Centro Nacional de Avaliação da Biodiversidade e Pesquisa e Conservação do Cerrado (CBC)  
Centro Nacional de Pesquisa e Conservação de Aves Silvestres (CEMAVE)  
Centro Nacional de Pesquisa e Conservação da Biodiversidade de Mamíferos Carnívoros (CENAP)  
Centro Nacional de Pesquisa e Conservação de Primatas Brasileiros (CPB) 


Diretoria de Pesquisa, Avaliação e Monitoramento da Biodiversidade\
Centro Administrativo Setor Sudoeste - EQSW 103/104 Bloco D - 1º andar\
70670-350 - Brasília, DF\
Tel: 61 3341-9055 - Fax: 61 3341-9068\
www.icmbio.gov.br

*Programa Nacional de Monitoramento da Biodiversidade - Programa Monitora* 
*Subprograma Terrestre, Componente Florestal - Relatório 2014-2022 | 2024*
  
  ------------------------------------------------------------------------
  
Sinopse  

O relatório do Componente Florestal, subprograma Terrestre do Programa Nacional de Monitoramento da Biodiversidade – Programa Monitora, apresenta os resultados da aplicação dos protocolos básicos de monitoramento, de 2014 a 2022, para quatro alvos globais: plantas árboreas e arborescentes, borboletas frugívoras, mamíferos terrrestres de médio e grande porte e aves terrícolas cinegéticas.  


SUPERVISÃO TÉCNICA E REVISÃO FINAL\
Rodrigo Silva Pinto Jorge  
Dárlison Fernandes Carvalho de Andrade  

CATALOGAÇÃO E NORMALIZAÇÃO BIBLIOGRÁFICA\
Lucia Lanari Ozolins ??????

CAPA\
Denys Sousa 

------------------------------------------------------------------------  


  <center>FICHA CATALOGRÁFICA</center>  

                
  <center>**Dados internacionais de Caralogação na Publicação (CIP)**</center>
  <center>**(Câmara Brasileira do Livro, SP, Brasil)**</center>
  
  <br>
  
  Programa Nacional de Monitoramento da Biodiversidade : programa monitora,
  subprograma terrrestre, componente florestal : relatório 2014-2022 / Monitora. --
  Brasília, DF : Instituto Chico Mendes - 
  ICMBio, 2024.
  
  Vários autores.
  Vários colaboradores.
  Bibliografia.
  ISBN 978-65-5693-024-4
  
  1. Biodiversidade - Brasil 2. Biodiversidade - Conservação 3. Conservação da
  natureza 4. Meio Ambiente 5. Monitoramento ambiental 
  6. Sustentabilidade ambiental I. Monitora.
  II. Título.
  
  21-91938                                           CDD-577.5
  
  ------------------------------------------------------------------------
  <center>**Índice para catálogo sistemático**</center>
  
  1. Biodiversidade : Aspectos ambientais ; Ecologia
      577.5
      
  ------------------------------------------------------------------------
  
  *Copyright* ICMBio 2024. *O conteúdo desta publicação não pode ser reproduzido, guardado pelo sistema "retrieval" ou transmitido de qualquer modo por qualquer outro meio, seja eletrônico, mecânico, de fotocópia, de gravação ou outros, sem mencionar a fonte.*
  
------------------------------------------------------------------------ 
